import {
  SiBootstrap,
  SiCss3,
  SiDocker,
  SiExpress,
  SiFramer,
  SiGit,
  SiGithubactions,
  SiHtml5,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiSass,
  SiSqlite,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVite,
  SiCloudinary,
} from "react-icons/si";

export const personalInfo = {
  name: "Hyosua Colléter",
  email: "colleterhyosua@gmail.com",
  github: "https://github.com/hyosua",
  linkedin: "https://linkedin.com/in/hyosua",
  profilePicture: "/profile.jpg",
  heroDescription: "hero.description",
  cvPath: "/cv-colleter.pdf",
};

export const workExperience = [
  {
    company: "La Poste",
    location: "Yerres (91)",
    position: "work.laposte.position",
    period: "2016 - Présent",
    achievements: [
      "work.laposte.achievements.1",
      "work.laposte.achievements.2",
      "work.laposte.achievements.3",
      "work.laposte.achievements.4",
      "work.laposte.achievements.5",
      "work.laposte.achievements.6",
    ],
  },
  {
    company: "Aximum (Groupe COLAS)",
    location: "Lannion (22)",
    position: "work.aximum.position",
    period: "Mar 2015 - Juin 2015",
    achievements: [
      "work.aximum.achievements.1",
      "work.aximum.achievements.2",
      "work.aximum.achievements.3",
      "work.aximum.achievements.4",
    ],
  },
  {
    company: "Teraqua",
    location: "St-Martin-des-Champs (29)",
    position: "work.teraqua.position",
    period: "Avr 2014 - Juin 2014",
    achievements: [
      "work.teraqua.achievements.1",
      "work.teraqua.achievements.2",
      "work.teraqua.achievements.3",
      "work.teraqua.achievements.4",
    ],
  },
];

export const education = [
  {
    institution: "education.miaw.institution",
    location: "Evry (91)",
    degree: "education.miaw.degree",
    period: "2025 - Présent",
    achievements: [
      "education.miaw.achievements.1",
      "education.miaw.achievements.2",
      "education.miaw.achievements.3",
    ],
  },
  {
    institution: "education.dut.institution",
    location: "Lannion (29)",
    degree: "education.dut.degree",
    period: "2013 - 2015",
    achievements: [
      "education.dut.achievements.1",
      "education.dut.achievements.2",
      "education.dut.achievements.3",
      "education.dut.achievements.4",
    ],
  },
];

export const skills = {
  frontendDevelopment: [
    { name: "React", icon: <SiReact /> },
    { name: "Next.js", icon: <SiNextdotjs /> },
    { name: "Typescript", icon: <SiTypescript /> },
    { name: "Tailwind CSS", icon: <SiTailwindcss /> },
    { name: "Bootstrap", icon: <SiBootstrap /> },
    { name: "SASS", icon: <SiSass /> },
    { name: "HTML", icon: <SiHtml5 /> },
    { name: "CSS", icon: <SiCss3 /> },
  ],
  backendDevelopment: [
    { name: "Node.js", icon: <SiNodedotjs /> },
    { name: "Express", icon: <SiExpress /> },
    { name: "Python", icon: <SiPython /> },
    { name: "PHP", icon: <SiPhp /> },
  ],
  databaseAndStorage: [
    { name: "PostgreSQL", icon: <SiPostgresql /> },
    { name: "MySQL", icon: <SiMysql /> },
    { name: "SQLite", icon: <SiSqlite /> },
    { name: "MongoDB", icon: <SiMongodb /> },
    { name: "Redis", icon: <SiRedis /> },
  ],
  cloudAndDevOps: [
    { name: "Docker", icon: <SiDocker /> },
    { name: "Vercel", icon: <SiVercel /> },
    { name: "CI/CD", icon: <SiGithubactions /> },
    { name: "Git", icon: <SiGit /> },
    { name: "Linux", icon: <SiLinux /> },
    { name: "Cloudinary", icon: <SiCloudinary /> },
  ],
  toolsAndServices: [
    { name: "Vite", icon: <SiVite /> },
    { name: "Framer Motion", icon: <SiFramer /> },
  ],
};

export const projects = [
  {
    title: "projects.cexquis.title",
    github: "https://github.com/hyosua/cadavre-exquis",
    description: [
      "projects.cexquis.description.1",
      "projects.cexquis.description.2",
    ],
    image: "/cexquis2.png",
    website: "https://cadavrexquis.fr",
    videoDesktop: "/videos/cexquis-c.webm",
    videoMobile: "/videos/cexquis-mobile-c.webm",
    context: "projects.cexquis.context",
    results: [
      "projects.cexquis.results.1",
      "projects.cexquis.results.2",
      "projects.cexquis.results.3",
    ],
    achievements: [
      "projects.cexquis.achievements.1",
      "projects.cexquis.achievements.2",
      "projects.cexquis.achievements.3",
      "projects.cexquis.achievements.4",
    ],
    stackChoices: [
      "projects.cexquis.stack.1",
      "projects.cexquis.stack.2",
      "projects.cexquis.stack.3",
      "projects.cexquis.stack.4",
      "projects.cexquis.stack.5",
      "projects.cexquis.stack.6",
    ],
    challenges: [
      "projects.cexquis.challenges.1",
      "projects.cexquis.challenges.2",
      "projects.cexquis.challenges.3",
    ],
    tags: ["Next.js", "TypeScript", "Redis", "Socket-io","React","Fly.io","Docker", "Tailwind CSS"],
  },
  {
    title: "projects.peakture.title",
    github: "https://github.com/hyosua/peakture",
    description: [
      "projects.peakture.description.1",
      "projects.peakture.description.2",
    ],
    image: "/peakture.png",
    website: "https://peakture.fr",
    videoDesktop: "/videos/peakture-c.webm",
    videoMobile: "/videos/peakture-mobile-c.webm",
    context: "projects.peakture.context",
    results: [
      "projects.peakture.results.1",
      "projects.peakture.results.2",
      "projects.peakture.results.3",
    ],
    achievements: [
      "projects.peakture.achievements.1",
      "projects.peakture.achievements.2",
      "projects.peakture.achievements.3",
      "projects.peakture.achievements.4",
    ],
    stackChoices: [
      "projects.peakture.stack.1",
      "projects.peakture.stack.2",
      "projects.peakture.stack.3",
      "projects.peakture.stack.4",
      "projects.peakture.stack.5",
      "projects.peakture.stack.6",
    ],
    challenges: [
      "projects.peakture.challenges.1",
      "projects.peakture.challenges.2",
      "projects.peakture.challenges.3",
    ],
    tags: [
      "React",
      "Mongodb",
      "Express",
      "Node.js",
      "Tailwind CSS",
      "Vite",
      "Framer Motion",
    ],
  },
  {
    title: "projects.gmblackqueen.title",
    github: "https://github.com/hyosua/GmBlackQueen",
    description: [
      "projects.gmblackqueen.description.1",
      "projects.gmblackqueen.description.2",
    ],
    image: "/gmblackqueen2.png",
    website: "https://gmblackqueen.fr",
    videoDesktop: "/videos/gmblackqueen-c.webm",
    videoMobile: "/videos/gmblackqueen-mobile-c.webm",
    context: "projects.gmblackqueen.context",
    stackChoices: [
      "projects.gmblackqueen.stack.1",
      "projects.gmblackqueen.stack.2",
      "projects.gmblackqueen.stack.3",
    ],
    achievements: [
      "projects.gmblackqueen.achievements.1",
      "projects.gmblackqueen.achievements.2",
      "projects.gmblackqueen.achievements.3",
      "projects.gmblackqueen.achievements.4",
    ],
    challenges: [
      "projects.gmblackqueen.challenges.1",
      "projects.gmblackqueen.challenges.2",
      "projects.gmblackqueen.challenges.3",
    ],
    results: [
      "projects.gmblackqueen.results.1",
      "projects.gmblackqueen.results.2",
      "projects.gmblackqueen.results.3",
    ],
    tags: ["HTML", "CSS", "Javascript", "Vanilla", "Swiper.js"],
  },
  {
    title: "projects.miaw.title",
    github: "https://github.com/hyosua/miaw/",
    description: ["projects.miaw.description.1", "projects.miaw.description.2"],
    image: "/miaw2.png",
    website: "https://miaw-techwear.fr/",
    videoDesktop: "/videos/miaw-c.webm",
    videoMobile: "/videos/miaw-mobile-c.webm",
    context: "projects.miaw.context",
    stackChoices: [
      "projects.miaw.stack.1",
      "projects.miaw.stack.2",
      "projects.miaw.stack.3",
    ],
    achievements: [
      "projects.miaw.achievements.1",
      "projects.miaw.achievements.2",
      "projects.miaw.achievements.3",
      "projects.miaw.achievements.4",
    ],
    challenges: [
      "projects.miaw.challenges.1",
      "projects.miaw.challenges.2",
      "projects.miaw.challenges.3",
    ],
    results: [
      "projects.miaw.results.1",
      "projects.miaw.results.2",
    ],
    tags: ["PHP", "MySql", "Wordpress", "Bootstrap"],
  },
  {
    title: "projects.uxgoodpatterns.title",
    github: "https://github.com/hyosua/ux-good-patterns",
    description: ["projects.uxgoodpatterns.description.1"],
    image: "/uxgoodpatterns.png",
    website: "https://uxgoodpatterns.com/",
    context: "projects.uxgoodpatterns.context",
    stackChoices: [
      "projects.uxgoodpatterns.stack.1",
      "projects.uxgoodpatterns.stack.2",
      "projects.uxgoodpatterns.stack.3",
      "projects.uxgoodpatterns.stack.4",
    ],
    achievements: [
      "projects.uxgoodpatterns.achievements.1",
      "projects.uxgoodpatterns.achievements.2",
    ],
    challenges: [
      "projects.uxgoodpatterns.challenges.1",
      "projects.uxgoodpatterns.challenges.2",
    ],
    results: [
      "projects.uxgoodpatterns.results.1",
      "projects.uxgoodpatterns.results.2",
      "projects.uxgoodpatterns.results.3",
    ],
    video: "",
    tags: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Astro"],
  },
];

export const awards = [
  {
    name: "awards.1.name",
    issuer: "awards.1.issuer",
    date: "Jan 2020",
    type: "awards.1.type",
    position: "awards.1.position",
  },
  {
    name: "awards.2.name",
    issuer: "awards.2.issuer",
    date: "Feb 2021",
    type: "awards.2.type",
    position: "awards.2.position",
  },
  {
    name: "awards.3.name",
    issuer: "awards.3.issuer",
    date: "Mar 2022",
    type: "awards.3.type",
    position: "awards.3.position",
  },
  {
    name: "awards.4.name",
    issuer: "awards.4.issuer",
    date: "Apr 2022",
    type: "awards.4.type",
    position: "awards.4.position",
  },
  {
    name: "awards.5.name",
    issuer: "awards.5.issuer",
    date: "May 2022",
    type: "awards.5.type",
    position: "awards.5.position",
  },
  {
    name: "awards.6.name",
    issuer: "awards.6.issuer",
    date: "Jun 2022",
    type: "awards.6.type",
    position: "awards.6.position",
  },
  {
    name: "awards.7.name",
    issuer: "awards.7.issuer",
    date: "Jul 2022",
    type: "awards.7.type",
    position: "awards.7.position",
  },
];